//! Cross-implementation V2 signing tests.
//!
//! Loads `tests/fixtures/v2_signing_vectors.json` (generated by
//! `scripts/gen_v2_test_vectors.py` and verified against
//! `eth_account.encode_typed_data` — the same path py-clob-client-v2 uses)
//! and asserts our Rust implementation produces byte-identical output for
//! every intermediate.
//!
//! TDD: tests are layered top-to-bottom — type hash, domain separator, struct
//! hash, EIP-712 digest, full signature. Each subsequent layer depends on the
//! previous one being correct.

use polymarket_taker::orders_v2::{
    self, OrderSubmission, OrderV2, SignedOrderV2, DOMAIN_NAME, DOMAIN_VERSION, ORDER_TYPE_STRING,
};
use serde::Deserialize;
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct Fixtures {
    _meta: Meta,
    vectors: Vec<Vector>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct Meta {
    description: String,
    domain_name: String,
    domain_version: String,
    order_type_string: String,
    domain_type_string: String,
    exchange_v2: String,
    neg_risk_exchange_v2: String,
    chain_id: u64,
}

#[derive(Debug, Deserialize)]
struct Vector {
    name: String,
    input: Input,
    expected: Expected,
}

#[derive(Debug, Deserialize)]
struct Input {
    privkey: String,
    chain_id: u64,
    exchange_address: String,
    #[allow(dead_code)]
    neg_risk: bool,
    order: OrderInput,
}

#[derive(Debug, Deserialize)]
struct OrderInput {
    salt: String,
    maker: String,
    signer: String,
    token_id: String,
    maker_amount: String,
    taker_amount: String,
    side: u8,
    signature_type: u8,
    timestamp: String,
    metadata: String,
    builder: String,
    expiration: String,
}

#[derive(Debug, Deserialize)]
struct Expected {
    type_hash: String,
    domain_separator: String,
    struct_hash: String,
    eip712_digest: String,
    signature: String,
    #[allow(dead_code)]
    json_body: serde_json::Value,
}

impl OrderInput {
    fn to_order_v2(&self) -> OrderV2 {
        OrderV2 {
            salt: self.salt.clone(),
            maker: self.maker.clone(),
            signer: self.signer.clone(),
            token_id: self.token_id.clone(),
            maker_amount: self.maker_amount.clone(),
            taker_amount: self.taker_amount.clone(),
            side: self.side,
            signature_type: self.signature_type,
            timestamp: self.timestamp.clone(),
            metadata: self.metadata.clone(),
            builder: self.builder.clone(),
            expiration: self.expiration.clone(),
        }
    }
}

fn load_fixtures() -> Fixtures {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("v2_signing_vectors.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("fixture JSON parse")
}

fn hex32(bytes: &[u8; 32]) -> String {
    format!("0x{}", hex::encode(bytes))
}

fn parse_hex32(s: &str) -> [u8; 32] {
    let stripped = s.strip_prefix("0x").unwrap_or(s);
    let bytes = hex::decode(stripped).expect("hex decode");
    assert_eq!(bytes.len(), 32, "expected 32 bytes, got {}", bytes.len());
    let mut out = [0u8; 32];
    out.copy_from_slice(&bytes);
    out
}

// ──────────────────────────────────────────────────────────────────────
// Layer 0: constants — verify our hardcoded strings match the fixture.
// ──────────────────────────────────────────────────────────────────────

#[test]
fn meta_constants_match_fixture() {
    let f = load_fixtures();
    assert_eq!(f._meta.domain_name, std::str::from_utf8(DOMAIN_NAME).unwrap());
    assert_eq!(f._meta.domain_version, std::str::from_utf8(DOMAIN_VERSION).unwrap());
    assert_eq!(f._meta.order_type_string, std::str::from_utf8(ORDER_TYPE_STRING).unwrap());
    assert_eq!(f._meta.exchange_v2, orders_v2::EXCHANGE_V2_STANDARD);
    assert_eq!(f._meta.neg_risk_exchange_v2, orders_v2::EXCHANGE_V2_NEG_RISK);
}

// ──────────────────────────────────────────────────────────────────────
// Layer 1: type hash — pure constant, identical across all vectors.
// ──────────────────────────────────────────────────────────────────────

#[test]
fn order_type_hash_matches_fixture() {
    let f = load_fixtures();
    let computed = hex32(&orders_v2::order_type_hash());
    for v in &f.vectors {
        assert_eq!(
            computed.to_lowercase(),
            v.expected.type_hash.to_lowercase(),
            "type hash mismatch on vector '{}'",
            v.name
        );
    }
}

// ──────────────────────────────────────────────────────────────────────
// Layer 2: domain separator — varies by exchange address.
// ──────────────────────────────────────────────────────────────────────

#[test]
fn domain_separator_matches_fixture() {
    let f = load_fixtures();
    for v in &f.vectors {
        let computed = hex32(&orders_v2::domain_separator(
            v.input.chain_id,
            &v.input.exchange_address,
        ));
        assert_eq!(
            computed.to_lowercase(),
            v.expected.domain_separator.to_lowercase(),
            "domain separator mismatch on '{}'",
            v.name
        );
    }
}

// ──────────────────────────────────────────────────────────────────────
// Layer 3: struct hash — depends on full order field encoding.
// ──────────────────────────────────────────────────────────────────────

#[test]
fn order_struct_hash_matches_fixture() {
    let f = load_fixtures();
    for v in &f.vectors {
        let order = v.input.order.to_order_v2();
        let computed = hex32(&orders_v2::order_struct_hash(&order));
        assert_eq!(
            computed.to_lowercase(),
            v.expected.struct_hash.to_lowercase(),
            "struct hash mismatch on '{}'",
            v.name
        );
    }
}

// ──────────────────────────────────────────────────────────────────────
// Layer 4: EIP-712 digest — keccak(0x1901 || domain || struct_hash).
// ──────────────────────────────────────────────────────────────────────

#[test]
fn eip712_digest_matches_fixture() {
    let f = load_fixtures();
    for v in &f.vectors {
        let dom = parse_hex32(&v.expected.domain_separator);
        let struct_h = parse_hex32(&v.expected.struct_hash);
        let computed = hex32(&orders_v2::eip712_digest(&dom, &struct_h));
        assert_eq!(
            computed.to_lowercase(),
            v.expected.eip712_digest.to_lowercase(),
            "digest mismatch on '{}'",
            v.name
        );
    }
}

// ──────────────────────────────────────────────────────────────────────
// Layer 5: full signature — ECDSA over digest with fixed privkey.
// ──────────────────────────────────────────────────────────────────────

#[test]
fn sign_order_matches_fixture() {
    let f = load_fixtures();
    for v in &f.vectors {
        let order = v.input.order.to_order_v2();
        let computed = orders_v2::sign_order(
            &v.input.privkey,
            &order,
            &v.input.exchange_address,
            v.input.chain_id,
        )
        .unwrap_or_else(|e| panic!("sign_order failed on '{}': {e}", v.name));
        assert_eq!(
            computed.to_lowercase(),
            v.expected.signature.to_lowercase(),
            "signature mismatch on '{}'",
            v.name
        );
    }
}

// ──────────────────────────────────────────────────────────────────────
// Layer 6: POST /order JSON body matches py-clob-client-v2 order_to_json_v2.
// ──────────────────────────────────────────────────────────────────────

#[test]
fn post_order_body_matches_fixture() {
    let f = load_fixtures();
    for v in &f.vectors {
        let order = v.input.order.to_order_v2();
        let signed = SignedOrderV2 {
            order,
            signature: v.expected.signature.clone(),
        };
        let owner = v
            .expected
            .json_body
            .get("owner")
            .and_then(|x| x.as_str())
            .expect("fixture json_body.owner")
            .to_string();
        let submission = OrderSubmission::new(&signed, owner, "GTC");

        let computed: serde_json::Value =
            serde_json::to_value(&submission).expect("serialize submission");
        let expected = &v.expected.json_body;

        assert_json_eq(&computed, expected, &format!("vector '{}'", v.name));
    }
}

/// Compare two JSON values for structural equality, ignoring case in hex
/// strings (signatures and bytes32 fields). Address checksums must match
/// exactly because that's what the API expects.
fn assert_json_eq(actual: &serde_json::Value, expected: &serde_json::Value, ctx: &str) {
    if actual != expected {
        let a = serde_json::to_string_pretty(actual).unwrap();
        let e = serde_json::to_string_pretty(expected).unwrap();
        panic!("JSON mismatch in {ctx}\n--- actual ---\n{a}\n--- expected ---\n{e}");
    }
}
